/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBG: typeof import('./src/components/AppBG.vue')['default']
    ImgEditor: typeof import('./src/components/ImgEditor.vue')['default']
    ImgUpload: typeof import('./src/components/ImgUpload.vue')['default']
  }
}
